version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: YourPassword1!
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./db:/var/opt/mssql
    user: 0:0
